=== hdgdink/XML/src/kz/javalab/Biker.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:attribute name="name" type="xs:string"/>
    <xs:element name="brand" type="xs:string"/>
    <xs:element name="weight" type="xs:double"/>
    <xs:element name="price" type="xs:double"/>
    <xs:element name="size" type="xs:double"/>
    <xs:element name="ventilation" type="xs:boolean"/>
    <xs:element name="type" type="xs:string"/>
    <xs:element name="material" type="xs:string"/>
    <xs:element name="colorOfVisor" type="xs:string"/>
    <xs:element name="buildInProtection" type="xs:boolean"/>

    <xs:element name="biker">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="boots" type="boots" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="gloves" type="gloves" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="helmet" type="helmet" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="jacket" type="jacket" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="pants" type="pants" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="equip">
        <xs:sequence>
            <xs:element ref="brand"/>
            <xs:element ref="weight"/>
            <xs:element ref="price"/>
            <xs:element ref="size"/>
            <xs:element ref="ventilation"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="boots">
        <xs:complexContent>
            <xs:extension base="equip">
                <xs:sequence>
                    <xs:element ref="type"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="gloves">
        <xs:complexContent>
            <xs:extension base="equip">
                <xs:sequence>
                    <xs:element ref="type"/>
                    <xs:element ref="material"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="helmet">
        <xs:complexContent>
            <xs:extension base="equip">
                <xs:sequence>
                    <xs:element ref="type"/>
                    <xs:element ref="colorOfVisor"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="jacket">
        <xs:complexContent>
            <xs:extension base="equip">
                <xs:sequence>
                    <xs:element ref="material"/>
                    <xs:element ref="buildInProtection"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="pants">
        <xs:complexContent>
            <xs:extension base="equip">
                <xs:sequence>
                    <xs:element ref="material"/>
                    <xs:element ref="buildInProtection"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


</xs:schema>

=== hdgdink/XML/src/kz/javalab/src/Biker.xml
<?xml version="1.0" encoding="UTF-8"?>
<biker name="Johan"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="Biker.xsd">
    <boots>
        <brand>Alpine</brand>
        <weight>3.5</weight>
        <price>215.35</price>
        <size>40.0</size>
        <ventilation>true</ventilation>
        <type>Sport</type>
    </boots>
    <gloves>
        <brand>Alpine</brand>
        <weight>0.6</weight>
        <price>80.0</price>
        <size>2.0</size>
        <ventilation>true</ventilation>
        <type>Sport</type>
        <material>Leather</material>
    </gloves>
    <helmet>
        <brand>ARAI</brand>
        <weight>1.58</weight>
        <price>326.0</price>
        <size>58.0</size>
        <ventilation>true</ventilation>
        <type>Street</type>
        <colorOfVisor>Transparent</colorOfVisor>
    </helmet>
    <jacket>
        <brand>DAINESE</brand>
        <weight>1.23</weight>
        <price>180.54</price>
        <size>48.0</size>
        <ventilation>true</ventilation>
        <material>Cevlar</material>
        <buildInProtection>true</buildInProtection>
    </jacket>
    <pants>
        <brand>DAINESE</brand>
        <weight>1.5</weight>
        <price>190.15</price>
        <size>48.0</size>
        <ventilation>false</ventilation>
        <material>Cevlar</material>
        <buildInProtection>true</buildInProtection>
    </pants>
</biker>

=== hdgdink/XML/src/kz/javalab/Biker.xml
<?xml version="1.0" encoding="UTF-8"?>
<biker name="Johan"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="Biker.xsd">

    <boots>
        <type/>
        Sport
        <brand/>
        Alpine
        <weight/>
        3.5
        <price/>
        215.35
        <size/>
        40
        <ventilation/>
        true
    </boots>

    <gloves>
        <type/>
        Sport
        <brand/>
        Alpine
        <material/>
        Leather
        <weight/>
        0.6
        <price/>
        80
        <size/>
        2
        <ventilation/>
        true
    </gloves>

    <helmet>
        <type/>
        Street
        <colorOfVisor/>
        Transparent
        <brand/>
        ARAI
        <weight/>
        1.58
        <price/>
        326
        <size/>
        58
        <ventilation/>
        true
    </helmet>

    <jacket>
        <material/>
        Cevlar
        <buildInProtection/>
        true
        <brand/>
        DAINESE
        <weight/>
        1.23
        <price/>
        180.54
        <size/>
        48
        <ventilation/>
        true
    </jacket>

    <pants>
        <material/>
        Cevlar
        <buildInProtection/>
        true
        <brand/>
        DAINESE
        <weight/>
        1.5
        <price/>
        190.15
        <size/>
        48
        <ventilation/>
        false
    </pants>

</biker>
